version: '2'

services:
  nginx:
    build:
      context: https://github.com/LongTaiJun/Docker-Nginx.git
    restart: always
    privileged: true
    image: longtaijun/nginx:latest
    ports:
    - "80:80"
    volumes:
    - /data/nginx:/data/wwwroot
    - /etc/localtime:/etc/localtime
